#!/usr/bin/env bash
cp /media/pi/BACKUPRWK2/minisegway_rpi_config/interfaces_krauss_home /etc/network/interfaces
cp /media/pi/BACKUPRWK2/minisegway_rpi_config/wpa_supplicant_krauss_home.conf /etc/wpa_supplicant/wpa_supplicant.conf
